### ISSUE TITLE
Improve Accessibility 

### ISSUE THREAD

**Issue by yons101** [yons101/hotel101-hotel-bookings-laravel-react#2]

**Comment by C-Zekeri** [comment]
Hi! I'd like to get to work on this issue. Anything I should know before I get started?

**Comment by yons101** [comment]
Hello! nothing really, just that this project is using Tailwind CSS

**Comment by C-Zekeri** [comment]
Awesome.
I won't be fiddling much with the CSS anyway. I'll be working on all accessibility issues I can find except colour contrast because I don't want to mess with your design scheme.
I'm already on it, and hope to be done by tomorrow.
Thank you!

Oh, I'd also like to know if you have test login details so I can inspect the user dashboard for accessibility issues?

**Comment by yons101** [comment]
Try this : test_user@gmail.com:123456789

**Comment by C-Zekeri** [comment]
Alright, thanks.
